import data from "@/data/stationFootprints.json";
import type { StationFootprint, StationFootprintData } from "./stationFootprints.build";

// Generated by `npm run data:footprints`; see stationFootprints.build.ts.
export const STATION_FOOTPRINT_DATA = data as StationFootprintData;

const byStation = new Map<string, StationFootprint[]>();
for (const footprint of STATION_FOOTPRINT_DATA.footprints) {
  byStation.set(footprint.stationId, [...(byStation.get(footprint.stationId) ?? []), footprint]);
}

/** Every surveyed footprint for a station (interchanges often have one per line). Empty when none exists. */
export function footprintsForStation(stationId: string): readonly StationFootprint[] {
  return byStation.get(stationId) ?? [];
}
